findpkgs: WIP - not executable yet

diff --git a/findpkgs b/findpkgs
--- a/findpkgs
+++ b/findpkgs
@@ -117,7 +117,7 @@ declare br8link="http://download.devel.redhat.com/brewroot/repos/rhel-8.0-build/
 
 declare pkg="os/Packages"
 declare topdir=		# dir where rh7 and rh8 subdirs are created
-declare tdindex		# index to first dir after topdir/rh[7|8], which is where the
+declare -i tdindex		# index to first dir after topdir/rh[7|8], which is where the
 			# : path to the packages starts.
 declare -a rh8stream=(
 "Supplementary"
@@ -435,6 +435,58 @@ buildtrees() {
 	done
 }
 
+# extract_pkgname
+#
+# Extracts the package name from the line, which is the second
+# field after the colon in each line formatted as the following
+# example.
+#
+#  ../tmp/rh8/Server/pkglist:mpich-3.0
+#
+#
+extract_pkgname() {
+	echo "$1" | awk -F ":" '{print $2}'
+}
+
+# extract_strmname()
+#
+# Extracts the name of the stream, e.g. Server, Workstation, from
+# a line formatted as the following example.
+#
+#  ../tmp/rh8/Server/pkglist:mpich-3.0
+#             ^^^^^^
+#            Stream name
+#
+# Globals
+#   tdindex
+#
+extract_strmname() {
+
+	# tdindex is 0-based, but the fields in cut are 1-based,
+	# ergo the +1.
+	#
+	echo "$1" | cut -d'/' -f$((tdindex+1))
+}
+
+# extract_rhel() - determines whether pkg line is from rhel7 or rhel8
+#
+# Assumes that pline is formatted as in the following example
+#   topdir/rhel7/Server/pkglist:mpich
+#
+# Globals
+#   tdindex - index to the top of the path for the distro
+#
+# Arguments
+#   $1 - pline, path line
+#
+extract_rhel() {
+	local pline="$1"
+	local rheldir
+
+	rheldir=$(echo "$pline" | cut -d'/' -f$tdindex)
+	echo ${rheldir: -1}
+}
+
 # process_stream()
 #
 # Globals
@@ -495,68 +547,138 @@ process_stream() {
 	done
 }
 
+# rm_arches() - remove the arch component of the path in each string of pkgstr
+#
+# Globals
+#   tdindex - 0-based index to the stream component, e.g. Workstation, Server,
+#             in each string of the string-of-strings for the packages.
+#
 rm_arches() {
-	local pkgstr="$1"
-	local retstr
+	local pkgstr="$1"	# string of strings generated by grep for the package
+	local retstr		# string of strings that will be returned
+	local findex=$((tdindex+2))	# index in each path string to the arch
 
+	# The BUILDROOT directory does not have an arch component
+	#
 	retstr=$(
 		while read line; do
 			[[ $line == *BUILDROOT* ]] \
 				&& { echo "$line "; continue;} \
-				|| echo $(echo $line | cut --complement -d'/' -f5)
-		done <<< $flap
+				|| echo $(echo $line | cut --complement -d'/' -f$findex)
+		done <<< "$pkgstr"
 		)
-	eval "$2='$retstr'"
+	echo "$retstr"
 }
 
+# sort_pkgs - sort the string-of-strings for ordered parsing
+#
+# First sort unique on the stream component, e.g. Server, Workstation, so we
+# have only one package per stream.
+# Then sort on the package so that they are all grouped for orderly parsing.
+#
+# Globals
+#   tdindex - 0-based index to the stream component of the path to the package
+#
 sort_pkgs() {
-	local pkgstr="$1"
-	local tmpstr
-	local retstr
+	local pkgstr="$1"	# string-of-strings from the grep pkg
+	local tmpstr		# scratch
+	local retstr		# returned string-of-strings
 
-	tmpstr=$(echo "$pkgstr" | sort -t'/' -k $tdindex)
+	tmpstr=$(echo "$pkgstr" | sort -u -t'/' -k $tdindex)
 	retstr=$(echo "$tmpstr" | sort -t':' -k2)
 
-	eval "$2='$retstr'"
+	echo "$retstr"
 }
 
+# fill_hypharray - fills an array of hyphenated packages for a given distro
+#
+# Arguments
+#   pkgstr - This is a string generated by grepping for hyphenated packages.
+#            It is comprised of strings separated by IFS, one string for
+#            each hyphenated package discovered. Additionally there can be
+#            more than one genus of hypenated package, e.g. mpich-devel
+#            mpich-doc, mpich-autoload, etc.
+#
+# Globals
+#   tdindex - 0-based index to path of each package on each line of pkgstr
+#   farray  - an array intended to contain the strings extrackted from
+#             pkgstr to be printed to the screen.
+#
 fill_hypharray() {
-	local pkgstr="$1"
-	local mnt="$2"
-	local distro=$3
-	local apkg
-	local prev
-	local pdir
-	local tstr
+	local pkgstr="$1"	# sorted package string-of-strings
+	local mnt="$2"		# maintainer
+	local distro
+	local apkg		# package name extracted from each line
+	local prev		# previous package name in the loop
+	local pdir		# dir path to the package
+	local tstr		# scratch string to be added to array
+	local line		# string captured in each loop pass
 
 	while read line; do
 
-		# Get the directory where the package is located
-		# fields in cut are 1-based, not 0-based, ergo tdindex+1
-		#
-		pdir=$(echo "$line" | cut -d'/' -f$((tdindex+1)))
-		apkg=$(echo "$line" | awk -F ":" '{print $2}')
+		pdir=$(extract_strmname "$line") # location of pkg
+		apkg=$(extract_pkgname "$line")  # name of pkg
+		distro=$(extract_rhel "$line")   # 7 or 8
 
 		if [[ $apkg != $prev ]]; then
-			tstr=$(printf "%-32s%s\n" $apkg $mnt
+			
+			tstr=$(printf "\n%-32s%s\n" $apkg $mnt
 			farray+=("$tstr")
 		fi
 
 		tstr=$(printf "    RHEL-$distro %s\n" $pdir)
 		farray+=("$tstr")
-
+		prev="$apkg"
+	done <<< "$pkgstr"
 }
 
+# check_other - check the string-of-strings in the other distro for
+#               presence or absence of a given package
+#
+# At this point, we have two strings-of-strings, one for rhel7 and
+# one for rhel8.
+#
 check_other() {
-	local apkg="$1"
-	local pkgstr="$2"
-	local stream
-	local b_found
+	local apkg="$1"		# Name of the package to grep in pkgstr
+	local pkgstr="$2"	# string-of-strings to be grept for apkg
+	local distro=$3		# 7 or 8
+	local stream		# string-of-strings generated by grep for apkg
+	local stat		# return status from bash calls
+	local tstr		# scratch string
+	local line		# string read each pass of loop
+	local sname		# stream name, e.g. Server, Workstation
 
-	stream=$(echo $grep ^$pkg$ 
+	stream=$(echo "$pkgstr" | $grep $apkg$)
+	stat=$?
+
+	if [ $stat -eq 0 ]; then
+		while read line; do
+			sname=$(extract_strmname "$line")
+			tstr=$(printf "    RHEL-$distro %s\n" "$sname"
+			farray+=("$tstr")
+		done <<< "$stream"
+	else
+		farray+=("    RHEL-$distro NOT FOUND")
+	fi
+
 }
 
 # get_hyphpkgs() - get the hyphenated anciallary packages of the pkg
+#
+# There can be more than one hyphenated package for a given package.
+# For example, grepping for mpich with a hyphen, "mpich-", will create
+# a string of strings separated by IFS for mpic-devel, mpich-3.0-autoload,
+# mpich-doc, etc, each string containing the path in the distro to the
+# package.
+# Additionally, the patch also contains the arch for which the package
+# was built. This function will call the rm_arches function to remove
+# the arch portion of the path from each string in the string-of-strings,
+# so that the string-of-strings can then be sorted for unique paths at
+# the top level, e.g. Server, Workstation, etc, so that one path for each
+# instance of the package is preserved in the string-of-strings and sorted
+# by path.
+# For example, all of the Worstation/[arch]/package strings will be reduced
+# to simpley one Workstation/package string in the string-of-strings.
 #
 # Globals
 #   topdir	- passed as argument $2 to this script
@@ -565,29 +687,22 @@ check_other() {
 get_hyphpkgs() {
 	local pkg="$1"
 	local mnt="$2"
-	local distro=$3
-	local dary
-	local fee7
-	local fee8
-	local fie7
-	local fie8
-	local foe7
-	local foe8
+	local fee	# grept packages in rhel8 and rhel8 distros
+	local fie
+	local foe
+	local fum
 	local pary7
 	local pary8
 	local b_found=false
 
-	fee7=$(grep -r -m1 ^$pkg- $topdir/rh7)	# all the instances in rh7
-	fee8=$(grep -r -m1 ^$pkg- $topdir/rh7)	# all the instances in rh8
-
-	rm_arches "$fee7" fie7		# remove the arch component of the path
-	rm_arches "$fee8" fie8
-
-	sort_pkgs "$fie7" foe7		# sort unique on paths, and then sort
-	sort_pkgs "$fie8" foe8		# : on package
+	fee=$(grep -r -m1 ^$pkg- $topdir)	# generate string-of-strings
+	fie=$(rm_arches "$fie")		# remove arch component of the path
+	foe=$(sort_pkgs "$fie") 	# sort unique on paths and pkg
 
 	pary7=($(echo "$foe7"))		# convert to arrays
 	pary8=($(echo "$foe8"))
+
+
 
 }
 
