patchtools: gorp: WIP: integrate patchtool
Signed-off-by: Tony Camuso <tcamuso@redhat.com>

diff --git a/gorp b/gorp
--- a/gorp
+++ b/gorp
@@ -1941,6 +1941,29 @@ get_originhead() {
 	dnorighead="$(get_cfg_item dnorighead)"
 }
 
+#** get_x11devel - dnf install libX11-devel if possible
+#
+get_x11devel() {
+
+	# No libX11-devel present, so we will have to install.
+	# Before we can try to dnf install libX11-devel, we need to know
+	# if user has superuser privileges.
+	sudo -n true || {
+		echo -e "
+$CAU$USER$INF does not have privileges to install libx11-devel$OFF
+"
+		return 1
+	}
+
+	# If the user has sudoer privileges, let's install libX11-devel.
+	sudo dnf install -y libX11-devel || {
+		echo -e "\n${CAU}Could not dnf install$STA libX11-devel$OFF\n"
+		return 0
+	}
+
+	return 0
+}
+
 #** is_xrunning - determine if x is running
 #
 # X needs to be running so that the application's windows can materialize
@@ -1953,12 +1976,18 @@ get_originhead() {
 #
 #*
 is_xrunning() {
-	# Define a temporary directory for compilation
-	local tmpdir=$(mktemp -d)
-	local xtest_c="$tmpdir/x_test.c"
-	local xtest_bin="$tmpdir/x_test"
+	local xtest_c="$MYDIR/x_test.c"
+	local xtest_bin="$MYDIR/x_test"
 
-	# Write the C code to a file
+	# If we don't already have the xtest binary, then build it.
+	[ -x "$xtest_bin" ] || {
+ 
+		# Before we build it, we need to be certain that we have the
+		# libX11-devel first, and, if we don't, the user has sudoer
+		# privs to dnf install it.
+		rpm -q libX11-devel > /dev/null 2>&1 || get_x11devel
+
+		# Write the C code to a file
 cat << 'EOF' > "$xtest_c"
 #include <X11/Xlib.h>
 #include <stdio.h>
@@ -1973,18 +2002,17 @@ int main(void) {
     return 1;  // No X server
 }
 EOF
-	# Compile the program (you can change gcc options as needed)
-	gcc "$xtest_c" -o "$xtest_bin" -lX11 >/dev/null 2>&1
+		# Compile the program (you can change gcc options as needed)
+		gcc "$xtest_c" -o "$xtest_bin" -lX11 >/dev/null 2>&1
+	}
 
 	# Check if the binary exists and is executable, then run it.
-	if [ -x "$xtest_bin" ] && "$xtest_bin"; then
+	if "$xtest_bin"; then
 	    echo "X server is available."
 	else
 	    echo "No X server found."
 	fi
-
-	# Clean up if you like (or leave for debugging)
-	rm -rf "$tmpdir"
+}
 
 #** get_backport_mode: choose which of the availiable backport modes to use
 #
