patchtools: gorp: more patchpal integration
This time I think we've got it.
Added two new functions:
  is_backport_done: was using the 'git apply --reverse --check' line
                    a lot to determine whether the backport had been
		    successfully completed. Need to test this before
		    invoking any patching software, again when we are
		    staging commits, and again when we are exiting by
		    ctrl-c.
  is_upcmt_marked : important when exiting by ctrl-c. If the backport
                    was completed, but the corresponding commit in the
		    backport file was not marked, then mark it as done
		    on the way out.

Also added a gawk stanza in stage_patchpal to insert text into the
commit log for JIRA and CVE links, Upstream Status, Conflicts, etc.

Signed-off-by: Tony Camuso <tcamuso@redhat.com>

diff --git a/gorp b/gorp
--- a/gorp
+++ b/gorp
@@ -1869,7 +1869,7 @@ backport() {
 	echo -e "${INF}Processing : $STA${commit:0:$wcols}$OFF"
 
 	# If this upstream commit has already been applied, return now.
-	git apply --reverse --check  < <(git show "$uphash") > /dev/null 2>&1 && {
+	is_backport_done && {
 		echo -e "$STA$uphash$INF already committed.$OFF"
 		mark_done "$uphash"
 		set_cfg_item "lastuphash" "$uphash"
@@ -1939,7 +1939,14 @@ backport() {
 		flag_conflict "$uphash"
 	fi
 
-	stage_commit
+	# We process differently for patchpal.
+	# If stage_patchpal doesn't return 0, then return with its status.
+	if ((backport_mode == bm_patchpal )); then
+		stage_patchpal || return $?
+	else
+		stage_commit
+	fi
+
 	get_lastuplog		# inits lastuphash from backport file
 	return 0;
 }
@@ -1957,7 +1964,8 @@ backport() {
 #		  str_cve
 #		  str_upstream
 #		  str_conflicts
-#       RETURNS:  none
+#       RETURNS:  0 all good
+#                 1 for patchpal retry
 #*
 stage_commit() {
 	ui_log "stage_commit"
@@ -1970,14 +1978,9 @@ stage_commit() {
 	# If this upstream commit has been committed external to stage_commit,
 	# then flag it.
 	#
-	git apply --reverse --check  < <(git show "$uphash") > /dev/null 2>&1 && {
+	is_backport_done && {
 		echo -e "$STA$uphash$INF was committed externaly.$OFF"
 		b_committed=true
-	}
-
-	# If we're using patchpal, then process that differently.
-	((backport_mode == bm_patchpal )) && {
-		stage_patchpal && return
 	}
 
 	# Create the new commit message in a file consisting of ..
@@ -2065,34 +2068,46 @@ stage_commit() {
 #  and brew info, if any.
 #  Query the user to see if editing the commit is warranted, for conflicts, etc.
 #
-#     ARGUMENTS:  1 - b_committed: indicates this upstream commit has been
-#                     committed.
+#     ARGUMENTS:
 #
 #       GLOBALS:  cmtmsgfile
 #		  str_jira
 #		  str_cve
 #		  str_upstream
 #		  str_conflicts
-#       RETURNS:  0 if no further action, 1 if action needed
+#       RETURNS:  0 if all is well
+#                 1 for patchpal not done
 #*
 stage_patchpal() {
 	ui_log "stage_patchpal"
-	local b_committed="$1"
 	local description=
 	local uphash=$currentuphash
 	local -i line=
 
-	! $b_committed {
-		# Do something here"
-		echo -e
+	# If the backport was not completed, then tell the user and
+	# try again.
+	is_backport_done || {
+		echo -e "${CAU}
+patchpal$INF backport of $STA$uphash$INF was not completed.
+You must press \"${STA}Accept$INF\" and \"${STA}Commit$INF\" in the \
+patchpal tool dialog in order
+to proceed to the next upstream commit.
+You can press$CAU ctrl-c$OFF any time to safely exit.
+$OFF"
 		return 1
 	}
 
 	set -f	# disable wildcards
-
 	git log -1 > "$cmtmsgfile"
-	$ line=$(grep -n -E -m2 '^[[:space:]]*commit [0-9a-fA-F]{40}$' foo \
+set -x
+	# Find the second instance of "commit <40-char-hash> in the
+	# git log. This is where the upstream commit log is appended
+	# to this downstream commit log.
+	line=$(grep -n -E -m2 '^[[:space:]]*commit [0-9a-fA-F]{40}$' "$cmtmsgfile" \
 		| tail -n1 | cut -d: -f1)
+
+	# Insert new stuff above this line, so backup one.
+	line=$((line - 1))
 
 	description="
 "
@@ -2114,7 +2129,6 @@ stage_patchpal() {
 	}
 	$b_crlf && description+="
 "
-
 	export ins="$description"
 	gawk -i inplace -v target="$line" '
 	{
@@ -2127,10 +2141,55 @@ stage_patchpal() {
 	  print;
 	}
 	' "$cmtmsgfile"
-
+set +x
 	set +f	# re-enable wildcards
-
 	mark_done "$uphash"
+	return 0
+}
+
+#** is_backport_done
+#
+# Tests whether the upstream backport was done.
+#
+# Globals
+#   currentuphash - the upstream commit hash being backported
+#
+# Returns
+#   0 - if upstream backport was completed
+#   1 - if not
+#*
+is_backport_done() {
+	local uphash="$currentuphash"
+
+	# Following line returns 0 if the upstream commit has already been
+	# backported by doing a dry run of reversing the upstream commit
+	# as a patch.
+	# If the test shows that it can be reversed, then the backport of
+	# that upstream hash is done, so it will return 0.
+	# It the test shows that the patch cannot be reversed, then it
+	# will return a 1, indicating that the backport was not done.
+	#
+	git apply --reverse --check  < <(git show "$uphash") > /dev/null 2>&1
+	return $?
+}
+
+#** is_upcmt_marked
+#
+# Look int the backports file to see if the current upstream hash has been
+# marked as done.
+#
+# Globals
+#   currentuphash
+#   backportfile
+#
+# Returns
+#   0 - if marked done
+#   1 - if not
+#*
+is_upcmt_marked() {
+	[ -f "$backportfile" ] || return 0
+	grep -E "^\+ ${currentuphash}\b" "$backportfile"
+	return $?
 }
 
 #** set_cfg_item key value: writes the value to the key in the .conf file
@@ -2697,6 +2756,14 @@ ctrl_c() {
 	ui_log "ctrl_c"
 	set +x
 	echo
+d
+	# If user pressed ctrl-c, and the backport was committed but
+	# was left unmarked, then mark it as done now.
+	if is_backport_done && ! is_upcmt_marked; then
+		mark_done "$currentuphash"
+		set_cfg_item "lastuphash" "$currentuphash"
+	fi
+
 	validate_last_upstream_hash
 	exit_gorp $CTLC_EXIT         # defined in lib/ui.source
 }
