patchtools: missingfixes: improvements
Accept any valid upstream tag.

Check validity of tag entered by user.

Much better checking on whether the commits in the missing-commits
file were committed before the given upstream tag.

Added an -a option to print all the missing tags detected.

Signed-off-by: Tony Camuso <tcamuso@redhat.com>

diff --git a/missingfixes b/missingfixes
--- a/missingfixes
+++ b/missingfixes
@@ -15,20 +15,22 @@ declare missing_file=
 declare usagestr=$(
 cat <<EOF
 
-$(basename $0) upstream-tag
+$(basename $0) [-a] | [upstream-tag]
 
 Description:
 
   Parses the missing_fixes generated by patchreview for fixes that were made
-  before the optional upstream-tag.
+  before the given upstream-tag.
 
   NOTE:
        Must be executed in a git repo directory that has executed the
        patchreview script.
 
 Arguments:
-  upstream-tag - upstream tag to check against. rc and dash  numbers will
-                 be ignored.
+  upstream-tag - Any valid upstream tag.
+
+Options:
+  -a : Show all the missing fixes detected. Tag will be ignored.
 
 \0
 EOF
@@ -101,31 +103,54 @@ extract_number() {
 	echo ${str:0:3}
 }
 
+show_all() {
+	while read line; do
+		echo $line | grep -q Missing || continue
+		echo $line | cut -d' ' -f5-
+	done < $missing_file
+
+	exit 0
+}
+
+commit_in_tag() {
+	local commit="$1"
+	local tag="$2"
+
+	git rev-list $tag | grep -m1 $(git rev-parse $commit) > /dev/null 2>&1
+	return $?
+}
+
 main() {
 	local utag=$1
-	local tag
-	local ltag
+	local mypid
+	local findmsg="${INF}Checking $STA "
 
-	[ ${#@} -eq 1 ] || usage
+	[ ${#@} -ge 1 ] || usage
 
 	init
+
+	[ "$1" == "-a" ] && show_all
+
 	cd $remote_dir
 
-	utag=$(extract_number $utag)
+	git tag | grep -q -x $utag
+	[ $? -eq 0 ] || {
+		echo -e "${WRN}Tag $utag is not in this upstream kernel branch.$OFF"
+		cd - > /dev/null 2>&1
+		exit 1
+	}
 
 	while read line; do
 		echo $line | grep -q Missing || continue
-		lrc=0
 		commit=$(echo $line | cut -d' ' -f5)
-		tag=$(git tag --contains $commit | head -1)
-		[ -n "$tag" ] || continue
-		[ "${tag:0:1}" == "v" ] || continue
 
-		tag="${foo:0:5}"
-		ltag=$(extract_number $tag)
-		[ $ltag -gt $utag ] && continue
+		commit_in_tag $commit $utag &
+		mypid=$!
+		ui_waitonproc_tty $mypid .05 # "$findmsg$commit$OFF"
 
-		echo -en "${INF}Missing fix from $STA$tag$INF : "
+		[ $? -eq 0 ] || continue
+
+		echo -en "${INF}Missing fix from $STA$utag$INF : "
 		echo -e $line$OFF | cut -d' ' -f5-
 	done < $missing_file
 
