mkworkdir: AI assisted fixes and cleanup
Deprecated mkworkdir-noq, because I will make this version interactive
with a -i option in the near future.

Signed-off-by: Tony Camuso <tcamuso@redhat.com>

diff --git a/mkworkdir b/mkworkdir
--- a/mkworkdir
+++ b/mkworkdir
@@ -56,128 +56,124 @@ declare -a errmsg=(
 "Cannot find VFree in vgs fields."
 )
 
-errexit() {
-	local code "$1"
+# exitme
+#
+# Arguments
+#   $1 - exit code
+#   $2 - optional message
+#
+exitme() {
+	local -i code="$1"
+	local msg="$2"
 
+	((code == 0)) && exit "$code"
 	echo -e "$msg"
-	exit $code
+	usage
+	exit "$code"
 }
 
-strindex() {
-    local x="${1%%$2*}";
-    [[ $x = "$1" ]] && echo -1 || echo ${#x}
-}
+update_fstab() {
+	local dir="$1"
+	local map="$2"
+	local fstr
+	local uid
+	local fline
 
-aryindex() {
-    local -n ar=$1
-    local fld="$2"
-    local -n ix=$3
+	uid="$(blkid "$map" | tr -d \" | awk -F" " '{print $2}')"
+	fstr="$uid $dir                   xfs     defaults        0 0"
+	fline="$(grep -n "[[:space:]]$dir[[:space:]]" /etc/fstab | cut -d: -f1)"
 
-    for ((ix = 0; ix < ${#ar[@]}; ix++))
-    do
-        [ "${ar[ix]}" == "$fld" ] && break;
-    done
+	# If the line already exists in the fstab, delete it, because
+	# we're going to replace it.
+	[ -n "$fline" ] && sed -i.bak "$fline"d /etc/fstab
 
-    ((ix < ${#ar[@]})) && return 0 || return 1
+	echo "$fstr" >> /etc/fstab
 }
 
 main() {
-	local yn=
-	local lvsfldary # array of field names in lvs output
-	local lvhome	# line with home dir info in lvs ouput
-	local vgnameidx	# index to volume group name in lvs output
-	local vghome	# volume group that contains the /home directory
-	local lvsizeidx # index to the LSize field in lvs output
+        # The following line will single step through this script.
+        # Use the # to comment it out.
+        # trap 'read -p "$(printf "%$((${#BASH_SOURCE[0]}+8))s" "")" \
+	#	line && eval "$line" || exit $?' DEBUG
+
 	local homesiz	# size of the home directory extracted from lvs
+	# /dev/mapper names
+	local homemap	# e.g. /dev/mapper/rhel_dell--per440--01-home
+	local workmap	# e.g. /dev/mapper/rhel_dell--per440--01-work
+	# uuid extracted from blkid
+	local homeid	# uuid of /dev/mapper/rhel_dell--per440--01-home
+	local workid	# uuid of /dev/mapper/rhel_dell--per440--01-work
+	# fstab entries
+	local homefs	# fstab entry for /home
+	local workfs	# fstab entry for /work
+	local line
 
 	[[ "$1" == *"h"* ]] && usage
 
-	echo -e "$warning"
-	read
+	# If not the root, exit with an error code.
+	(( $(id -u) == 0 )) || exitme 1 "Must be root user to run this script"
 
 	# Find which logical volume is the home directory
 	#
-	homemnt="$(grep home /etc/fstab)"
+	homemnt=$(awk '$2=="/home" { print }' /etc/fstab)
+
 	[ $? -eq 0 ] || {
-		echo "Can't find \'home\' in /etc/fstab"
-		exit 1
+		exitme 1 "Can't find \'home\' in /etc/fstab"
 	}
 
 	# Create temporary workmnt by replacing 'home' with 'work'
 	# in the home string grepped from /etc/fstab
 	#
 	workmnt="${homemnt//home/work}"
-	homedir="$(echo $homemnt | awk -F " " '{print $2}')"
-	workdir="${homedir//home/work}"
 
-	# Get the volume group that contains the home directory and get the
-	# current size of the home directory (home logical volume).
-	# 1. Get the lvs listing field names
-	# 2. Get the index to the VG field in the lvs list
-	# 3. Find the logical volume for the home directory in the lvs list
-	# 4. Get the Volume Group name from the VG field of home logical vol
-	# 5. Get the home logical volume size from the LSize field
-	# 6. Truncate the decimal and remove non-numeric chars from homesiz
-	#
-	read -ra lvsfldary <<< $(lvs | head -1) 	# 1st line has field names
-	read -ra lvhome <<< $(lvs --unit g | grep home) # /home fields
-	aryindex lvsfldary "VG" vgnameidx
-	aryindex lvsfldary "LSize" lvsizeidx
-	vghome="${lvhome[vgnameidx]}"		# volume group for /home
-	homesiz="${lvhome[lvsizeidx]%.*}"	# Lsize of /home
-	homesiz="${homesiz//[!0-9]}"		# :
+	homedir=$(awk '$2=="/home" { print $2 }' /etc/fstab)
+	workdir="/work"
 
-	# echo the parameters before continuing.
-	#
-	echo "/home Volume Group Name : $vghome"
-	echo "-----------------------"
-	echo "The /home directory will be resized to make room for /work"
-	echo "homedir: $homedir"
-	echo "homemnt: $homemnt"
-	echo
-	echo "The /work directory will be created and added to /etc/fstab."
-	echo "workdir: $workdir"
-	echo "workmnt: $workmnt"
-	read -p "Press ctrl-c to exit or any other key to continue ..."
-	echo "Current homedir size: $homesiz GB"
+	# 1. Get the device backing /home from fstab
+	homemap="$(awk '$2=="/home" { print $1 }' /etc/fstab)"
 
-	while :; do
-		read -p "Enter new homedir size in GB: " newhomesiz
-		echo "The new homedir will be $newhomesiz GB"
-		((newhomesiz < $homesiz)) || {
-			echo "New homedir size must be less than $homesiz"
-			continue
-		}
-		worksiz=$((homesiz - newhomesiz))
-		echo "The workdir size will be $worksiz GB"
-		read -n1 -p "Is this what you want (y/n) : " yn
-		[ "$yn" == "y" ] && break
-	done
-	echo
+	# 2. Derive the VG name by stripping “-home” off the mapper basename
+	vgname="$(basename "$homemap")"
+	vgname="${vgname%-home}"
+
+	homemap="/dev/mapper/${vgname}-home"
+	workmap="/dev/mapper/${vgname}-work"
+
+	# 3. Pull the /home LV size (in GB, integer)
+	homesiz="$(
+	  lvs --noheadings --units g \
+	      -o lv_size "${vgname}/home" \
+	    | awk '{ print int($1) }'
+	)"
+
+	# 4. Compute new sizes
+	newhomesiz=$(( homesiz / 2 ))
+	worksiz=$(( homesiz - newhomesiz ))
+
+	# 5. Debug output
+	echo "VG name:      $vgname"
+	echo "Current size: ${homesiz}G"
+	echo "New /home:    ${newhomesiz}G"
+	echo "/work:        ${worksiz}G"
 
 	umount -v -l "$homedir"
-	lvremove -v "$homedir"
-	lvcreate -v -L "${newhomesiz}"G -n home "$vghome"
-	lvcreate -v -L "${worksiz}"G -n work "$vghome"
+	lvremove -v /dev/"$vgname"/home
+	lvcreate -v -L "${newhomesiz}"G -n home "$vgname"
+	lvcreate -v -L "${worksiz}"G -n work "$vgname"
 
-	homedir=$(find /dev/mapper/ | grep home)
-	workdir=$(find /dev/mapper/ | grep work)
-
-	mkfs.xfs "$homedir"
-	mkfs.xfs "$workdir"
+	mkfs.xfs "$homemap"
+	mkfs.xfs "$workmap"
 	[ -d /home ] || mkdir /home
 	[ -d /work ] || mkdir /work
 
-	grep $workdir /etc/fstab || {
-		cp -v /etc/fstab /etc/fstab.orig
-		echo "$workmnt" >> /etc/fstab
-	}
+	update_fstab "/home" "$homemap"
+	update_fstab "/work" "$workmap"
 
-	mount -v "$homedir"
-	mount -v "$workdir"
+	systemctl daemon-reload
+	mount /home
+	mount /work
+	mount -a
 
-	lvextend -l +100%FREE "$workdir"
-	xfs_growfs "$workdir"
 	restorecon -R /work
 	restorecon -R /home
 }
