patchreview: add refinements and fixes
- shopt -s extglob for extened shell pattern matches
- use extended pattern matching to delete all but log files from outdir
- add commentary to some of the more obscure functions
- fix bug in retry_patch(). Need to strip away directory information
  from patch file name before using the name to create a .retry log
  in the outdir.
- abort processing on git am error in apply_patches()

diff --git a/patchreview b/patchreview
--- a/patchreview
+++ b/patchreview
@@ -22,6 +22,10 @@
 # ~/bin/renpat
 # ~/bin/patcmp
 
+# Enable extglob for more specific directory actions
+#
+shopt -s extglob
+
 #######################################
 # External Source Files
 #######################################
@@ -209,7 +213,10 @@ function set_booleans {
 }
 
 # replace_patch
-# $1 - total patches
+#
+# GLOBALS
+#	outdir
+#	us_commits
 #
 function replace_patch {
 	local patnum
@@ -229,7 +236,7 @@ function clean_patches {
 }
 
 function clean_dir {
-	clean_patches "$1"
+	rm -vf "$1"/!(*.log);
 }
 
 function clean_directories {
@@ -239,7 +246,7 @@ function clean_directories {
 	getyn "$delquery\n\t$indir\n\t$outdir\n" response
 	if $response; then
 		rm -vf "$indir"/*
-		clean_patches "$outdir"
+		rm -vf "$outdir"/!(*.log)
 	fi
 }
 
@@ -346,9 +353,7 @@ function menu_loop {
 	indir=$(prj_get_item $prj_indir)
 	outdir=$(prj_get_item $prj_outdir)
 	mailclient=$(prj_get_item $prj_mailclient)
-
 	commit_msg_file="$outdir/commit-msg.txt"
-	echo $commit_msg_file
 
 	# delete any "scratch" file from the indir
 	#
@@ -399,12 +404,24 @@ function check_gitam {
 	fi
 }
 
+# strindex string-1 string-2
+#
+# Return zero-based index of string-2 in string-1
+# Returns -1 if string-2 is not found in string-1
+#
 function strindex {
 	x="${1%%$2*}"
 	[[ $x = $1 ]] && echo -1 || echo ${#x}
 }
 
-
+# create_commit_msg
+#
+# $1 - pathname of patch
+#
+# GLOBALS
+#	outdir
+#	commit_msg_file
+#
 function create_commit_msg {
 	local diffstr="diff "
 	local subjstr="Subject: "
@@ -426,22 +443,44 @@ function create_commit_msg {
 	done < "$1"
 }
 
+# retry_patch
+#
+# $1 - pathname of patch
+#
+# GLOBALS
+#	outdir
+#	commit_msg_file
+#
 function retry_patch {
+	local retrystat
+	local retryname=$(basename -s .patch "$1")
+
 	create_commit_msg "$1"
-	patch --fuzz=3 -p1 < "$1" 2>&1 | tee "$outdir"/"$1".retry
-	if [ $? -ne 0 ]; then
+	patch --fuzz=3 -p1 < "$1" 2>&1 | tee "$outdir"/"$retryname".retry
+	retrystat=$?
+	if [ $retrystat -ne 0 ]; then
 		echo "Unable to apply "$1""
 		echo "Exiting script with nonzero status"
 		echo
 		exit 1
 	fi
-	commit . -F "$commit_msg_file"
+	git commit . -F "$commit_msg_file"
+	# git log --pretty -n1
+	# read -n1
 }
 
+# apply_patches
+#
+# GLOBALS
+#	indir
+#	outdir
+#	bp_commits
+#
 function apply_patches {
 	# patchcount is global
 	local stat=0
 	echo "" > "$outdir/$bp_commits"
+
 	# for patch in $(ls $indir/*.patch); do
 	for patch in $(ls -1 "$indir"/*.patch | sort -V); do
 		let patchcount++
@@ -456,7 +495,11 @@ function apply_patches {
 #			[ $stat -ne 0 ] && break
 #		fi
 
-		[ $stat -ne 0 ] && retry_patch "$patch"
+		if [ $stat -ne 0 ]; then
+			git am --abort
+			$b_gitam_err_abort && exit 1
+			retry_patch "$patch"
+		fi
 
 		printf "%3d " $patchcount >> "$outdir/$bp_commits"
 		git log --oneline -n1 >> "$outdir/$bp_commits"
@@ -500,7 +543,7 @@ echo -en "$attr_OFF"
 # Parameter Initialization
 ###########################################
 
-# Declare the variables we will be using
+# Declare the global variables we will be using
 #
 declare prj_entries=0
 declare index=0
