readlinen: rewrite with safety checks

diff --git a/readlinen b/readlinen
--- a/readlinen
+++ b/readlinen
@@ -1,12 +1,61 @@
 #!/bin/bash
 
-function read_nth_line {
-	awk -v line=$1 '{
-		if (NR == line) {
+# __isdigit - determines if $1 is a digit
+#
+# returns 0 if digit, 1 if not
+#
+# example:
+#
+# $(isdigit $foo) && echo yup || echo nope
+#
+__isdigit() {
+	[[ $1 =~ ^-?[0-9]+$ ]] && return 0 || return 1
+}
+
+
+__check_lineargs() {
+	local number=$1
+	local file="$2"
+	local lines
+	local argc=$#
+
+	[ $argc -eq 2 ] || return 1
+
+	__isdigit $number
+	[ $? -eq 0 ] || return 2
+
+	[ -f "$file" ] || return 3
+
+	lines=$(cat "$file" | wc -l)
+	((number > lines)) && return 4
+
+	return 0
+}
+
+# __readlinen - Reads one line in a file given the line number.
+# $1 - line number
+# $2 - file to read
+#
+# Returns nonzero on inconsistent input.
+#
+# call: line=$(ui_readline line file)
+#
+# The line of text will be echoed to stdout
+#
+function __readlinen {
+	local __line__
+	local stat
+
+	__check_lineargs $1 $2
+	stat=$?
+	[ $stat -eq 0 ] || return $stat
+
+	awk -v __line__="$1" '{
+		if (NR == __line__) {
 			print $0;
 		}
 	}' $2
 }
 
-line="$(read_nth_line $1 $2)"
+line="$(__readlinen $1 "$2")"
 echo "$line"
